
# ADD FONTS
font_family			JetBrainsMono Nerd Font
bold_font			auto
italic_font			auto
bold_italic_font		auto
font_size			15
	
# TEXT CURSOR CUSTOMIZATION
cursor				#aaffff
cursor_text_color		background
cursor_shape			beam
cursor_beam_thickness		2
cursor_blink_interval		0.5
cursor_stop_blinking_after	0
cursor_trail			1
cursor_trail_delay		0.5 0.5
cursor_trail_start_treshold	2
cursor_trail_color		#a17c04

# MOUSE
url_color			#a17c04
url_style			dotted
url_prefixes			file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# WINDOW LAYOUT
active_border_color		#a17c04
inactive_border_color		#cccccc

# Tab bar
tab_bar_edge			top
tab_bar_margin_width		0.8
tab_bar_margin_height		0.3 0.6
tab_bar_style			powerline
active_tab_foreground		#000
active_tab_background		#eee
active_tab_font_style		bold
inactive_tab_foreground		#444
inactive_tab_background		#999
inactive_tab_font_style		normal

# COLOR SCHEME
foreground			#74c7ec
background			#2d0922
background_opacity		0.7
background_blur			0
