			

# Switch between windows
# map				ctrl+shift+left neighboring_window left
# map				ctrl+shift+right neighboring_window right
# map				ctrl+shift+up neigboring_window up
# map				ctrl+shift+down neighboring_window down

# ADD FONTS
font_family			MesloLGS NF
bold_font			auto
italic_font			auto
bold_italic_font		auto
font_size			16
	
# TEXT CURSOR CUSTOMIZATION
cursor				#aaffff
cursor_text_color		background
cursor_shape			beam
cursor_beam_thickness		2
cursor_trail			1
cursor_trail_delay		0.5 0.5
cursor_trail_start_treshold	2
cursor_trail_color		#a17c04

# MOUSE
mouse_hide_await		0 0
url_color			#a17c04
url_style			dotted
url_prefixes			file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# WINDOW LAYOUT
active_border_color		#a17c04
inactive_border_color		#cccccc

# Tab bar
tab_bar_edge			top
tab_bar_margin_width		0.8
tab_bar_margin_height		0.3 0.6
tab_bar_style			powerline
active_tab_foreground		#000
active_tab_background		#eee
active_tab_font_style		bold
inactive_tab_foreground		#444
inactive_tab_background		#999
inactive_tab_font_style		normal

# COLOR SCHEME
foreground			#aaff88
background			#120915
background_opacity		0.9
background_blur			0
