
# ADD FONTS
# font_family			JetBrainsMono Nerd Font
# bold_font 			auto
# italic_font			auto
# bold_italic_font		auto
font_size	    		12
	
# Split Layout aktivieren
enabled_layouts splits

# TEXT CURSOR CUSTOMIZATION
# cursor_text_color		background
cursor_shape			beam
cursor_beam_thickness		2
cursor_blink_interval		0.5
cursor_stop_blinking_after	0
cursor_trail			1
cursor_trail_delay		0.5 0.5
cursor_trail_start_treshold	2

# MOUSE
# url_color			#a17c04
url_style			dotted
url_prefixes			file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# Tab bar
tab_bar_edge			top
tab_bar_margin_width		0.8
tab_bar_margin_height		0.3 0.6
tab_bar_style			powerline
active_tab_font_style		bold

# COLOR SCHEME
# background			#000000
# background_opacity		0.8
# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
